SimpleNIX

diff --git a/builder/core/linux-vblade/build b/builder/core/linux-vblade/build
--- a/builder/core/linux-vblade/build
+++ b/builder/core/linux-vblade/build
@@ -1,26 +1,67 @@
 #!/bin/sh
-clear; CUR=$(pwd); . /etc/init.d/tc-functions
-. ../functions.sh; GetProcessorType; export CFLAGS CXXFLAGS LDFLAGS
-SFX="x86"
-case $(uname -m) in
-    x86_64) SFX="x64"  ;;
-    armv*)  SFX="arm"  ;;
-    aarch*) SFX="arch" ;;
-    *)      SFX="misc" ;;
-esac
+TITLE="
+        ######
+       ##    ## ####
+       ##        ##  ##     ##
+        ######   ##  ###   ### ########
+             ##  ##  #### #### ##     ## ##
+       ##    ##  ##  ## ### ## ##     ## ##       ########
+        ######   ##  ##     ## ########  ##       ##
+                #### ##     ## ##        ##       ##             #####
+                     ##     ## ##        ##       ######        ##   ##
+                   #           ##        ##       ##            # 0 0 #
+  ######          ###                    ######## ##            #  V   #
+    ##             #                              ########    ##       ##
+    ##         ###    ### ####   ###    ###  ##### #####     #          ##
+    ##        #  ##    ###    ##  ##     ##    ##   ##      #            ##
+    ##       #   ##    ##     ##  ##     ##      ###        #  #      #  ###
+    ##          ###    ##     ##  ##     ##      ###       @@##        # #@@
+    ##       # ###     ##     ##  ##     ##     ## ##    @@@@@@#       #@@@@@@
+    ##      ## ### #   ##     ##  ###   ###    ##   ##   @@@@@@@# CDC #@@@@@@@
+  ############  ###   ####   ####   #### ### ##### #####   @@@@@#######@@@@@"
+#------------------------------------------------------------------------------#
+# This file is a part of a project which contains pieces from other projects   #
+# belonging to potentially hundreds of individuals globally in an effort to    #
+# bring together some of the best computing materials the world has to offer   #
+# under a single roof with an automated core allowing a tailor-made experience #
+# like no other. Some of these pieces may have originated from individuals,    #
+# while others may have come from public distributions such as Alpine, Apache, #
+# CentOS, Debian, Fedora, SlackWare, TinyCore, Zorin, etc. just to name a few. #
+# This project will be ever changing throughout the entire Version 0.x.x life- #
+# cycle and should NOT be considered a complete and/or functional system.      #
+#------------------------------------------------------------------------------#
+clear; echo "${TITLE}"; echo; CUR=$(pwd)
+. /etc/init.d/tc-functions; . ../functions                             ##### TCL
+SFX=$(GetProcessorType); SXX=${SFX/x86_/x}; export CFLAGS CXXFLAGS LDFLAGS
 
 
 
 
 
-APP="vblade"
-VER="25"
+  ##########################
+ #/ LINUX - AoE - VBlade /#
+################################################################################
+# ATA Over Ethernet, or AoE, is a network protocol developed by the Brantley   #
+# Coile Company, designed for simple, high-performance access of block storage #
+# devices over Ethernet networks.  It is used to build storage area networks   #
+# (SANs) with low-cost, standard technologies. It is especially useful in the  #
+# creation of PXE based installations and some virtual installations allowing  #
+# virtual hard drive storage to be served from other machines while being safe #
+# from prying eyes, as it cannot be accessed from the outside world.           #
+################################################################################
+# VBlade is the tool necessary to create shared storage blocks for other       #
+# devices/machines to utilize.                                                 #
+################################################################################
+EXT_NAME="vblade"
+EXT_VERS="25"
 
 echo
-echo "${MAGENTA}${APP} ${CYAN}Version ${VER} ${SFX}${NORMAL}"
+echo "${YELLOW}EXTENSION: ${CYAN}${EXT_NAME}"
+echo "${YELLOW}VERSION  : ${CYAN}${EXT_VERS} ${GREEN}${SXX}"
+echo
 echo -n "${WHITE}Support Extensions: ${NORMAL}"
 
-EXTS="compiletc squashfs-tools"
+EXTS="compiletc squashfs-tools"                                       ##### TCL
 for EXT in $EXTS
 do
     echo -n "${EXT} "
@@ -30,45 +71,69 @@ done
 echo
 
 
-### SOURCE ARCHIVE ###
-[ ! -f ${APP}-${VER}.zip ] && wget https://github.com/OpenAoE/${APP}/archive/refs/tags/${APP}-${VER}.zip
-[ ! -d ${APP}_${VER}_${SFX} ] && unzip ${APP}-${VER}.zip && mv ${APP}-${APP}-${VER} ${APP}_${VER}_${SFX}
-[ ! -f ${APP}-${VER}.sns ] && cd $CUR/${APP}_${VER}_${SFX} && mksquashfs $CUR/${APP}_${VER}_${SFX} $CUR/${APP}_${VER}.sns
+### SOURCE CODE ###
+if [ ! -f $CUR/src/${EXT_NAME}-${EXT_VERS}.zip ]; then
+    echo "${MAGENTA}Downloading source code${NORMAL}"
+    mkdir -p $CUR/src; cd $CUR/src
+    wget -q https://github.com/OpenAoE/${EXT_NAME}/archive/refs/tags/${EXT_NAME}-${EXT_VERS}.zip
+    if [ ! -f $CUR/src/${EXT_NAME}-${EXT_VERS}.zip ]; then
+        echo "${RED}ERROR! ${YELLOW}Download Failed!${NORMAL}"; echo
+        wget https://github.com/OpenAoE/${EXT_NAME}/archive/refs/tags/${EXT_NAME}-${EXT_VERS}.zip
+        exit 1
+    fi
+fi
 
-cd $CUR/${APP}_${VER}_${SFX}
-make || exit 1
-strip --strip-all $CUR/${APP}_${VER}_${SFX}/${APP}
+### SOURCE DIRECTORY ###
+if [ ! -d $CUR/src/${EXT_NAME}_${EXT_VERS} ]; then
+    echo "${MAGENTA}Extracting source code${NORMAL}"
+    cd $CUR/src
+    unzip ${EXT_NAME}-${EXT_VERS}.zip >/dev/null 2>&1
+    mv ${EXT_NAME}-${EXT_NAME}-${EXT_VERS} ${EXT_NAME}_${EXT_VERS}
 
-mkdir -p /tmp/build/${APP}/usr/local/bin
-mkdir -p /tmp/build/${APP}/usr/local/sbin
+    if [ ! -f $CUR/${EXT_NAME}_${EXT_VERS}.nix.src ]; then
+        echo "${MAGENTA}Creating Source Package${NORMAL}"
+        mkdir -p $CUR/src/pkg/usr/local/src/${EXT_NAME}
+        cp $CUR/src/${EXT_NAME}_${EXT_VERS}/* $CUR/src/pkg/usr/local/src/${EXT_NAME}/ -R
+        cd $CUR/src; mksquashfs pkg $CUR/${EXT_NAME}_${EXT_VERS}.nix.src > $CUR/src_squash.log 2>&1
+#        cd $CUR; rm $CUR/src/pkg -fR
+    fi
+fi
 
-cp $CUR/${APP}_${VER}_${SFX}/vblade /tmp/build/${APP}/usr/local/sbin/
-cp $CUR/${APP}_${VER}_${SFX}/vbladed /tmp/build/${APP}/usr/local/sbin/
-cp $CUR/${APP}_${VER}_${SFX}/sparsefile /tmp/build/${APP}/usr/local/bin/
+cd $CUR/src/${EXT_NAME}_${EXT_VERS}
+time make -j$(nproc) > $CUR/app_compile.log 2>&1 || exit 1
+strip --strip-all $CUR/src/${EXT_NAME}_${EXT_VERS}/${EXT_NAME}
 
-cd /tmp/build/${APP}
-mksquashfs /tmp/build/${APP} $CUR/${APP}_${VER}_${SFX}.snx
+mkdir -p /tmp/build/${EXT_NAME}/usr/local/bin
+mkdir -p /tmp/build/${EXT_NAME}/usr/local/sbin
+
+cp $CUR/src/${EXT_NAME}_${EXT_VERS}/vblade /tmp/build/${EXT_NAME}/usr/local/sbin/
+cp $CUR/src/${EXT_NAME}_${EXT_VERS}/vbladed /tmp/build/${EXT_NAME}/usr/local/sbin/
+cp $CUR/src/${EXT_NAME}_${EXT_VERS}/sparsefile /tmp/build/${EXT_NAME}/usr/local/bin/
+
+cd /tmp/build
+mksquashfs ${EXT_NAME} $CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.nix > $CUR/app_squash.log 2>&1
 cd $CUR
-md5sum ${APP}_${VER}_${SFX}.snx > $CUR/${APP}_${VER}_${SFX}.md5
-SIZE=$(ls -la $CUR/${APP}_${VER}_${SFX}.snx | awk '{print $5}')
+md5sum ${EXT_NAME}_${EXT_VERS}_${SXX}.nix > $CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.md5
+SIZE=$(ls -la $CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.nix | awk '{print $5}')
 [ $SIZE -gt 1024 ] && SZX="KB" && SIZE=$(expr $SIZE / 1024)
 [ $SIZE -gt 1024 ] && SZX="MB" && SIZE=$(expr $SIZE / 1024)
 [ $SIZE -gt 1024 ] && SZX="GB" && SIZE=$(expr $SIZE / 1024)
 
-FN=$CUR/${APP}_${VER}_${SFX}.info
-echo "Title:          $APP.tcz" > $FN
-echo "Description:    $APP ATA Over Ethernet Daemon" >> $FN
-echo "Version:        $VER" >> $FN
+FN=$CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.nfo
+echo "Title:          ${EXT_NAME}_${EXT_VERS}_${SXX}.nix" > $FN
+echo "Description:    $EXT_NAME ATA Over Ethernet Daemon" >> $FN
+echo "Version:        $EXT_VERS" >> $FN
 echo "Author:         Ed Cashin, Anderw Basterfield" >> $FN
 echo "Original-site:  http://github.com/OpenAoE" >> $FN
 echo "Copying-policy: Copyright (C) 2005 to Current" >> $FN
 echo "Size:           $SIZE $SZX" >> $FN
 echo "Extension_by:   CentralWare Development Centers" >> $FN
 echo "Tags:           ATA Over Ethernet AoE" >> $FN
-echo "Comments:       Compiled With SimpleNix $(version) kernel $(uname -r | awk -F- '{print $1}') ${SFX}" >> $FN
+echo "Comments:       Compiled With SimpleNix $(version) kernel $(uname -r | awk -F- '{print $1}') ${SXX}" >> $FN
 echo "Current:        $(date '+%F%n') by CentralWare" >> $FN
 echo "Change-log:     ----" >> $FN
+echo "Depends:        " >> $FN
 
-cd /tmp/build/${APP}
-find . -type f > $CUR/${APP}_${VER}_${SFX}.files
-sed -i 's/.\/usr/\/usr/g' $CUR/${APP}_${VER}_${SFX}.files
+cd /tmp/build/${EXT_NAME}
+find . -type f > $CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.lst
+sed -i 's/.\/usr/\/usr/g' $CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.lst
diff --git a/builder/core/linux-zfs/build b/builder/core/linux-zfs/build
--- a/builder/core/linux-zfs/build
+++ b/builder/core/linux-zfs/build
@@ -1,18 +1,50 @@
 #!/bin/sh
-clear; CUR=$(pwd); . ../functions
+TITLE="
+        ######
+       ##    ## ####
+       ##        ##  ##     ##
+        ######   ##  ###   ### ########
+             ##  ##  #### #### ##     ## ##
+       ##    ##  ##  ## ### ## ##     ## ##       ########
+        ######   ##  ##     ## ########  ##       ##
+                #### ##     ## ##        ##       ##             #####
+                     ##     ## ##        ##       ######        ##   ##
+                   #           ##        ##       ##            # 0 0 #
+  ######          ###                    ######## ##            #  V   #
+    ##             #                              ########    ##       ##
+    ##         ###    ### ####   ###    ###  ##### #####     #          ##
+    ##        #  ##    ###    ##  ##     ##    ##   ##      #            ##
+    ##       #   ##    ##     ##  ##     ##      ###        #  #      #  ###
+    ##          ###    ##     ##  ##     ##      ###       @@##        # #@@
+    ##       # ###     ##     ##  ##     ##     ## ##    @@@@@@#       #@@@@@@
+    ##      ## ### #   ##     ##  ###   ###    ##   ##   @@@@@@@# CDC #@@@@@@@
+  ############  ###   ####   ####   #### ### ##### #####   @@@@@#######@@@@@"
+#------------------------------------------------------------------------------#
+# This file is a part of a project which contains pieces from other projects   #
+# belonging to potentially hundreds of individuals globally in an effort to    #
+# bring together some of the best computing materials the world has to offer   #
+# under a single roof with an automated core allowing a tailor-made experience #
+# like no other. Some of these pieces may have originated from individuals,    #
+# while others may have come from public distributions such as Alpine, Apache, #
+# CentOS, Debian, Fedora, SlackWare, TinyCore, Zorin, etc. just to name a few. #
+# This project will be ever changing throughout the entire Version 0.x.x life- #
+# cycle and should NOT be considered a complete and/or functional system.      #
+#------------------------------------------------------------------------------#
+clear; CUR=$(pwd); OLD=$CUR; . /etc/init.d/tc-functions; . ../functions;       ##### TCL
+echo "${CYAN}${TITLE}${NORMAL}"; echo; SFX=$(GetProcessorType)
+SXX=${SFX/x86_/x}; export CFLAGS CXXFLAGS LDFLAGS
 
-################
-## ./build kernel=6.1.2 version=2.1.15
-##
-## * ZFS VERSION will be what ever CURRENT is if not specified
-## * ZFS VERSION MUST be 2.0.x or newer - 0.x.x is not supported
-##   and 1.x.x doesn't seem to exist on OpenZFS' website??
-## * KERNEL VERSION will be what ever CURRENT is if not specified
-## * KERNEL PATH must be THIS_PATH/../KERNEL-VERSION
-## * If KERNEL is not already compiled, it will be treated as NEW
-##
+  #############################
+ #/ LINUX - ZFS File System /#
+################################################################################
+# DESCRIPTION TO BE ADDED
+################################################################################
 
-ExtLoad compiletc perl5 ncursesw-dev bc bash mpc-dev udev-lib-dev texinfo coreutils glibc_apps gettext python3.6 elfutils-dev zsync wget automake autoconf libtirpc-dev libtool-dev pkg-config openssl-dev
+ExtLoadQuiet wget
+
+CPU=$(GetProcessorType); PLT="64"; [ "$(echo $CPU | grep 64)" == "" ] && PLT=""
+echo "${CYAN}OpenZFS ${WHITE}::: ${YELLOW}ZFS For Linux${NORMAL}"
+echo "${WHITE}=========================${NORMAL}"
 
 MAIN="https://github.com/openzfs/zfs/releases/download/zfs-[VER]/zfs-[VER].tar.gz"
 DOWN="https://github.com/openzfs/zfs/archive/refs/tags/zfs-[VER].tar.gz"
@@ -55,14 +87,44 @@ do
     esac
 done
 
-clear
-CPU=$(GetProcessorType); PLT="64"; [ "$(echo $CPU | grep 64)" == "" ] && PLT=""
-echo "${CYAN}OpenZFS ${WHITE}::: ${YELLOW}ZFS For Linux${NORMAL}"
-echo "${WHITE}=========================${NORMAL}"
 echo "${MAGENTA}ZFS VER${NORMAL}:  ${GREEN}v$VERSION${NORMAL}"
 echo "${MAGENTA}KERNEL${NORMAL} :  ${GREEN}v$KERNEL ${CYAN}${CPU}${NORMAL}"
+echo
 
-### Let's take care of ZFS sources first
+#########################
+#########################
+#### SOURCE : KERNEL ####
+#########################
+#######################################################################
+#### If we don't already have a kernel package ready for $KERNEL,  ####
+#### Let's COPY ../linux into ../linux-${KERNEL} and launch it     ####
+#### remotely.  This will build the entire kernel and modules, but ####
+#### saves us from having to do so separately!                     ####
+#######################################################################
+if [ ! -d ../linux-${KERNEL} ]; then
+    if [ ! -d $CUR/../linux ]; then
+        echo "${RED}ERROR! ${YELLOW}Linux Kernel Builder Missing!${NORMAL}"
+        exit 1
+    fi
+    echo
+    echo "${YELLOW}Preparing a fresh kernel build${NORMAL}"
+    cp $CUR/../linux $CUR/../linux-${KERNEL} -fR
+    echo "${YELLOW}Transferring to kernel build${NORMAL}"
+    cd $CUR/../linux-${KERNEL}
+    ./build remote version=${KERNEL}
+    echo
+    echo "${YELLOW}Continuing ZFS build${NORMAL}"
+fi
+
+######################
+######################
+#### SOURCE : ZFS ####
+######################
+######################
+CUR=$OLD; cd $CUR
+echo -n "${CYAN}Loading support extensions:"
+ExtLoad compiletc perl5 ncursesw-dev bc bash mpc-dev udev-lib-dev texinfo coreutils glibc_apps gettext python3.6 elfutils-dev zsync wget automake autoconf libtirpc-dev libtool-dev pkg-config openssl-dev squashfs-tools
+
 echo ""
 echo "${YELLOW}Gathering ZFS Source Code${NORMAL}"
 FILE="zfs-${VERSION}.tar.gz"
@@ -75,66 +137,190 @@ URL=${DOWN//\[VER\]/$VERSION}
 PTH=${FILE/.tar.gz/}
 [ ! -d ${PTH} ] && echo "${YELLOW}Extracting ZFS Source Code${NORMAL}" && tar -zxf ${FILE}
 
-### Let's check to see if our kernel source is also ready
-if [ ! -d ../kernel-${KERNEL} ]; then
-    # Download kernel source
-    if [ ! -f linux-${KERNEL}.tar.xz ]; then
-        echo "${YELLOW}Downloading Kernel v${KERNEL} Source Code${NORMAL}"
-        wget -q --no-check-certificate https://cdn.kernel.org/pub/linux/kernel/v${PREFIX}.x/linux-${KERNEL}.tar.xz || exit 1
-    fi
-    # Extract kernel source
-    if [ ! -d ../linux-${KERNEL} ]; then
-        echo "${YELLOW}Extracting Kernel v${KERNEL} Source Code${NORMAL}"
-        cd $CUR/..; tar -xf $CUR/linux-${KERNEL}.tar.xz || exit 1
-    fi
-fi
-
-### Kernel Configuration
-if [ ! -f $CUR/../linux-${KERNEL}/.config ]; then
-    ##### TODO: REPLACE WITH SIMPLENIX CONFIG #####
-    cd $CUR
-    wget -q -O tmp_cfg --no-check-certificate $(cat /opt/tcemirror)/14.x/${CPU}/release/src/kernel/
-    FILE=$(cat tmp_cfg | grep "config-" | awk -F "href=" '{print $2}' | awk '{print $1}')
-    FILE=${FILE//\'/}
-    wget -q --no-check-certificate -O linux-${KERNEL}-config $(cat /opt/tcemirror)/14.x/${CPU}/release/src/kernel/${FILE}
-    cp $CUR/linux-${KERNEL}-config $CUR/../linux-${KERNEL}/.config
-    rm tmp_cfg -f
-fi
-if [ ! -f $CUR/../linux-${KERNEL}/.config ]; then
-    echo "${RED}ERROR! ${MAGENTA}Kernel configuration file failed!${NORMAL}"
-    exit 1
-fi
-cp $CUR/../linux-${KERNEL}/.config $CUR/linux-${KERNEL}-config
-
-### KERNEL COMPILATION ###
-cd $CUR/../linux-${KERNEL}
-echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" > ./.blanks
-echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" >> ./.blanks
-echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" >> ./.blanks
-echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" >> ./.blanks
-echo "${YELLOW}Configuring kernel${NORMAL}"
-[ ! -f ./.config.ready ] && time make oldconfig < ./.blanks > $CUR/_kernel_config.log 2>&1 && touch ./.config.ready
-echo "${YELLOW}Compiling kernel${NORMAL}"
-[ ! -f ./.compiled ] && time make -j$(nproc) bzImage > $CUR/_kernel_compile.log 2>&1 && touch ./.compiled
-echo "${YELLOW}Compiling modules${NORMAL}"
-[ ! -f ./.modules ] && time make -j$(nproc) modules > $CUR/_kernel_modules.log 2>&1 && touch ./.modules
-
-
-
 
 ### ZFS
 echo "${YELLOW}Configuring ZFS${NORMAL}"
 cd $CUR/zfs-$VERSION || exit 1
 if [ ! -f ./configure ]; then
-    sh autogen.sh > $CUR/_zfs_autogen.log || exit 1
+    sh autogen.sh > $CUR/_zfs_autogen.log 2>&1 || exit 1
 fi
-time ./configure --with-linux=$CUR/../linux-${KERNEL} --prefix=/usr/local > $CUR/_zfs_configure.log || exit 1
-
-#make clean
+time ./configure --with-linux=$CUR/../linux-${KERNEL}/src/linux-${KERNEL} --prefix=/usr/local > $CUR/_zfs_configure.log 2>&1 || exit 1
 
 echo "${YELLOW}Compiling ZFS${NORMAL}"
 mkdir -p /tmp/zfs_v${VERSION}_k${KERNEL}
-make -s -j$(nproc) > $CUR/_zfs_compile.log  || exit 1
-make DESTDIR=/tmp/zfs_v${VERSION}_k${KERNEL} install > $CUR/_zfs_install.log 
-#sudo mv /tmp/zfs_v${VERSION}_k${KERNEL} $CUR/
-mv /tmp/zfs_v${VERSION}_k${KERNEL} $CUR/
+time make -s -j$(nproc) > $CUR/_zfs_compile.log 2>&1 || exit 1
+time make DESTDIR=/tmp/v${VERSION}_k${KERNEL} install > $CUR/_zfs_install.log 2>&1
+mv /tmp/v${VERSION}_k${KERNEL} $CUR/
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+exit
+
+
+
+
+
+
+echo
+echo -n "${WHITE}Support Extensions: ${NORMAL}"
+
+EXTS="compiletc squashfs-tools"                                       ##### TCL
+for EXT in $EXTS
+do
+    echo -n "${EXT} "
+    su -c "tce-load -w $EXT >/dev/null" tc
+    su -c "tce-load -i $EXT >/dev/null" tc
+done
+echo
+
+
+### SOURCE CODE ###
+if [ ! -f $CUR/src/${EXT_NAME}-${EXT_VERS}.zip ]; then
+    echo "${MAGENTA}Downloading source code${NORMAL}"
+    mkdir -p $CUR/src; cd $CUR/src
+    wget -q https://github.com/OpenAoE/${EXT_NAME}/archive/refs/tags/${EXT_NAME}-${EXT_VERS}.zip
+    if [ ! -f $CUR/src/${EXT_NAME}-${EXT_VERS}.zip ]; then
+        echo "${RED}ERROR! ${YELLOW}Download Failed!${NORMAL}"; echo
+        wget https://github.com/OpenAoE/${EXT_NAME}/archive/refs/tags/${EXT_NAME}-${EXT_VERS}.zip
+        exit 1
+    fi
+fi
+
+### SOURCE DIRECTORY ###
+if [ ! -d $CUR/src/${EXT_NAME}_${EXT_VERS} ]; then
+    echo "${MAGENTA}Extracting source code${NORMAL}"
+    cd $CUR/src
+    unzip ${EXT_NAME}-${EXT_VERS}.zip >/dev/null 2>&1
+    mv ${EXT_NAME}-${EXT_NAME}-${EXT_VERS} ${EXT_NAME}_${EXT_VERS}
+
+    if [ ! -f $CUR/${EXT_NAME}_${EXT_VERS}.nix.src ]; then
+        echo "${MAGENTA}Creating Source Package${NORMAL}"
+        mkdir -p $CUR/src/pkg/usr/local/src/${EXT_NAME}
+        cp $CUR/src/${EXT_NAME}_${EXT_VERS}/* $CUR/src/pkg/usr/local/src/${EXT_NAME}/ -R
+        cd $CUR/src; mksquashfs pkg $CUR/${EXT_NAME}_${EXT_VERS}.nix.src > $CUR/src_squash.log 2>&1
+#        cd $CUR; rm $CUR/src/pkg -fR
+    fi
+fi
+
+cd $CUR/src/${EXT_NAME}_${EXT_VERS}
+time make -j$(nproc) > $CUR/app_compile.log 2>&1 || exit 1
+strip --strip-all $CUR/src/${EXT_NAME}_${EXT_VERS}/${EXT_NAME}
+
+mkdir -p /tmp/build/${EXT_NAME}/usr/local/bin
+mkdir -p /tmp/build/${EXT_NAME}/usr/local/sbin
+
+cp $CUR/src/${EXT_NAME}_${EXT_VERS}/vblade /tmp/build/${EXT_NAME}/usr/local/sbin/
+cp $CUR/src/${EXT_NAME}_${EXT_VERS}/vbladed /tmp/build/${EXT_NAME}/usr/local/sbin/
+cp $CUR/src/${EXT_NAME}_${EXT_VERS}/sparsefile /tmp/build/${EXT_NAME}/usr/local/bin/
+
+cd /tmp/build
+mksquashfs ${EXT_NAME} $CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.nix > $CUR/app_squash.log 2>&1
+cd $CUR
+md5sum ${EXT_NAME}_${EXT_VERS}_${SXX}.nix > $CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.md5
+SIZE=$(ls -la $CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.nix | awk '{print $5}')
+[ $SIZE -gt 1024 ] && SZX="KB" && SIZE=$(expr $SIZE / 1024)
+[ $SIZE -gt 1024 ] && SZX="MB" && SIZE=$(expr $SIZE / 1024)
+[ $SIZE -gt 1024 ] && SZX="GB" && SIZE=$(expr $SIZE / 1024)
+
+FN=$CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.nfo
+echo "Title:          ${EXT_NAME}_${EXT_VERS}_${SXX}.nix" > $FN
+echo "Description:    $EXT_NAME ATA Over Ethernet Daemon" >> $FN
+echo "Version:        $EXT_VERS" >> $FN
+echo "Author:         Ed Cashin, Anderw Basterfield" >> $FN
+echo "Original-site:  http://github.com/OpenAoE" >> $FN
+echo "Copying-policy: Copyright (C) 2005 to Current" >> $FN
+echo "Size:           $SIZE $SZX" >> $FN
+echo "Extension_by:   CentralWare Development Centers" >> $FN
+echo "Tags:           ATA Over Ethernet AoE" >> $FN
+echo "Comments:       Compiled With SimpleNix $(version) kernel $(uname -r | awk -F- '{print $1}') ${SXX}" >> $FN
+echo "Current:        $(date '+%F%n') by CentralWare" >> $FN
+echo "Change-log:     ----" >> $FN
+echo "Depends:        " >> $FN
+
+cd /tmp/build/${EXT_NAME}
+find . -type f > $CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.lst
+sed -i 's/.\/usr/\/usr/g' $CUR/${EXT_NAME}_${EXT_VERS}_${SXX}.lst
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
